import React, { useEffect, useState } from "react";
import { useLocation } from "react-router-dom";
import "./Styles/ShowWeather.scss";
import axios from "axios";

const ShowWeather = () => {
  const location = useLocation();

  const [imageUrl, setImageUrl] = useState("");
  const getBackground = async (query) => {
    const accessKey = process.env.REACT_APP_UNSPLASH_ACCESS_KEY;
    const apiUrl = `https://api.unsplash.com/photos/random/?query=${query}&client_id=${accessKey}`;
    return axios
      .get(apiUrl, {
        headers: {
          Authorization: `${process.env.REACT_APP_UNSPLASH_ACCESS_TOKEN}`,
          // this token is created by using postman where i passed the
          // {
          //   "grant_type": "authorization_code",
          //   "client_id": "YOUR_ACCESS_KEY",
          //   "client_secret": "YOUR_SECRET_KEY",
          //   "redirect_uri": "http://localhost",
          //   "code": "YOUR_AUTHORIZATION_CODE"
          // }
          // in the header section and authorization code is generated by authorizing the redirected url
        },
      })
      .then((response) => {
        console.log(response.data);
        setImageUrl(response.data.urls.regular);
      })
      .catch((error) => {
        console.error(error);
      });
  };

  useEffect(() => {
    console.log(process.env.REACT_APP_UNSPLASH_ACCESS_TOKEN);
    getBackground(location.state.data[0].weather.description);
  }, []);

  return (
    <div
      style={{
        backgroundRepeat: "no-repeat",
        backgroundAttachment: "fixed",
        backgroundPosition: "center",
        backgroundSize: "cover",
        backgroundImage: `url(${imageUrl})`,
        height: "100vh",
        width: "100vw",
      }}
    >
      <h1
        style={{
          margin: 0,
          padding: "2% 5%",
        }}
      >
        Weather.<span>io</span>
      </h1>
      <div className="weather-info">
        <div>
          <span>City name: </span> {location.state.data[0].city_name}
        </div>
        <div>
          <span>Weather: </span> {location.state.data[0].weather.description}
        </div>
        <div>
          <span>Temperature: </span> {location.state.data[0].temp}
        </div>
        <div>
          <span>Date and Time: </span> {location.state.data[0].datetime}
        </div>
        {/* <div>{location.state.data[0].sunrise}</div>
      <div>{location.state.data[0].sunset}</div> */}
        <div>
          <span>TimeZone: </span> {location.state.data[0].timezone}
        </div>
      </div>
    </div>
  );
};

export default ShowWeather;
